apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service.name }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Values.service.name }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.service.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.service.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
