apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service.name }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Values.service.name }}
rules:
  - apiGroups:
      - "*"
    resources:
      - authcodes.dex.coreos.com
      - authrequests.dex.coreos.com
      - oauth2clients.dex.coreos.com
      - signingkeies.dex.coreos.com
      - refreshtokens.dex.coreos.com
      - passwords.dex.coreos.com
      - offlinesessionses.dex.coreos.com
      - connectors.dex.coreos.com
    verbs:
      - "*"
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Values.service.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.service.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.service.name }}
  apiGroup: rbac.authorization.k8s.io
