apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service.name }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Values.service.name }}
rules:
- apiGroups:
  - "dex.coreos.com"
  resources:
  - authcodes
  - authrequests
  - oauth2clients
  - signingkeies
  - refreshtokens
  - passwords
  - offlinesessionses
  - connectors
  - connectors
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Values.service.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.service.name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.service.name }}
  apiGroup: rbac.authorization.k8s.io
